table T_Clientes
	lineageTag: d1f1a3fe-287b-4ac8-bc21-75fcbb8e5047

	column Nombre_Cliente
		dataType: string
		lineageTag: 2bfd44e1-68a8-43aa-ae5f-1e2bdb46d05f
		summarizeBy: none
		sourceColumn: Nombre_Cliente

		annotation SummarizationSetBy = Automatic

	column ID_Cliente
		dataType: int64
		formatString: 0
		lineageTag: 2f24672a-2685-47d4-aa1a-882d9338b4dd
		summarizeBy: none
		sourceColumn: ID_Cliente

		annotation SummarizationSetBy = Automatic

	partition T_Clientes-b9fcd146-e641-4c8f-a7e5-dccddec0faf3 = m
		mode: import
		source =
				let
				    Source = Sql.Database(param_cnn, "lh_data"),
				    dbo_dimclientes = Source{[Schema="dbo",Item="dimclientes"]}[Data],
				    #"Tipo cambiado" = Table.TransformColumnTypes(dbo_dimclientes,{{"Nombre_Cliente", type text}, {"ID_Cliente", Int64.Type}})
				in
				    #"Tipo cambiado"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

