table T_Detalle_Pedido
	lineageTag: 6fc4786b-e921-450a-b64a-e436494095c8

	measure '1- Monto Total (Año)' = ```
			CALCULATE(SUM('T_Detalle_Pedido'[Monto Total]) , ALLEXCEPT('T_Detalle_Pedido', 'T_Factura'[Fecha_Creación].[Year], 'T_Factura'[Fecha_Creación].[Date] ) 
			
			)
			```
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 0060a77d-b184-47e4-a3a1-93adba645f05

	column Producto
		dataType: string
		lineageTag: 79d74530-c1b2-417d-a0a6-21f1b2227ab1
		summarizeBy: none
		sourceColumn: Producto

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column Categoría
		dataType: string
		lineageTag: 612e9750-935a-471b-b053-5cf6c2209ee3
		summarizeBy: none
		sourceColumn: Categoría

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column Cantidad
		dataType: int64
		formatString: 0
		lineageTag: 46419d55-dc61-4556-b057-a1b381fef633
		summarizeBy: sum
		sourceColumn: Cantidad

		annotation SummarizationSetBy = Automatic

	column Monto
		dataType: double
		lineageTag: 5f965a59-bf45-4e50-8130-bab6c5717ff0
		summarizeBy: sum
		sourceColumn: Monto

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Monto Total'
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 73ea6f1c-47de-4274-81e6-0a62bee56db0
		summarizeBy: sum
		sourceColumn: Monto Total

		annotation SummarizationSetBy = Automatic

	column 'Ventas Mayores a 50'
		dataType: string
		lineageTag: 15dbaf4c-2484-4e72-b5dd-b259c00c51c4
		summarizeBy: none
		sourceColumn: Ventas Mayores a 50

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column ID_Detalle_Pedido
		dataType: int64
		formatString: 0
		lineageTag: 5e62d6ad-da7d-4af1-9b76-ba8d0ec44638
		summarizeBy: sum
		sourceColumn: ID_Detalle_Pedido

		annotation SummarizationSetBy = Automatic

	column ID_Factura
		dataType: int64
		formatString: 0
		lineageTag: dbc0de95-b1c9-4477-87f2-5cf7bf0cea04
		summarizeBy: none
		sourceColumn: ID_Factura

		annotation SummarizationSetBy = Automatic

	column Sub_Categoria
		dataType: string
		lineageTag: b14530f1-5b3c-48b1-8c8c-1ee80038a9ad
		summarizeBy: none
		sourceColumn: Sub_Categoria

		annotation SummarizationSetBy = Automatic

	partition T_Detalle_Pedido-eee516b8-7f53-4f66-ba12-e5dc660e665a = m
		mode: import
		source =
				let
				    Source = Sql.Database(param_cnn, "lh_data"),
				    dbo_fact_detalle_pedido = Source{[Schema="dbo",Item="fact_detalle_pedido"]}[Data],
				    #"Tipo cambiado" = Table.TransformColumnTypes(dbo_fact_detalle_pedido,{{"ID_Detalle_Pedido", Int64.Type}, {"ID_Factura", Int64.Type}, {"Producto", type text}, {"Categoría", type text}, {"Sub_Categoria", type text}, {"Cantidad", Int64.Type}, {"Monto", type number}}),
				    #"Multiplicación insertada" = Table.AddColumn(#"Tipo cambiado", "Monto Total", each [Cantidad] * [Monto], type number),
				    #"Columna condicional agregada" = Table.AddColumn(#"Multiplicación insertada", "Ventas Mayores a 50", each if [Monto Total] > 50 then ">50" else "<=50")
				in
				    #"Columna condicional agregada"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

