table T_Territorio
	lineageTag: d5bce04d-5cea-42d3-81c8-ceff24c90279

	column IdTerritorio
		dataType: int64
		formatString: 0
		lineageTag: e5ac2fa6-4eff-4a87-b793-bb2b1740bbd8
		summarizeBy: none
		sourceColumn: IdTerritorio

		annotation SummarizationSetBy = Automatic

	column Pais
		dataType: string
		lineageTag: 30197f41-ef9b-4802-907b-8cc62921a660
		summarizeBy: none
		sourceColumn: Pais

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column Zona
		dataType: string
		lineageTag: 14786188-226d-4291-8666-5e26e907d79f
		summarizeBy: none
		sourceColumn: Zona

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column CodigoPais
		dataType: string
		lineageTag: 5bcac2bb-94bf-462a-a417-d9e963a96184
		summarizeBy: none
		sourceColumn: CodigoPais

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column Grupo
		dataType: string
		lineageTag: c09960a6-0586-41de-9b47-d4b29d481383
		summarizeBy: none
		sourceColumn: Grupo

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	partition T_Territorio-2800d9c5-6b40-48ff-9b40-315e5473d899 = m
		mode: import
		source =
				let
				    Source = Sql.Database(param_cnn, "lh_data"),
				    dbo_dimterritorios = Source{[Schema="dbo",Item="dimterritorios"]}[Data],
				    #"Tipo cambiado" = Table.TransformColumnTypes(dbo_dimterritorios,{{"IdTerritorio", Int64.Type}, {"Pais", type text}, {"Zona", type text}, {"CodigoPais", type text}, {"Grupo", type text}})
				in
				    #"Tipo cambiado"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

