name: Deploy Fabric Initial Workspace

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

permissions:
  contents: write  # NECESARIO para permitir el push



jobs:
  deploy-new-fabric-workspace:    
    runs-on: ubuntu-latest
    environment: PRO

    env:  
      ENVIRONMENT: "PRO"
      FABRIC_WORKSPACE_ID: ${{ secrets.FABRIC_WORKSPACE_ID }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install fabric-cicd
        run: |
          pip install fabric-cicd


      - name: Run Artifact update
        run: python ./scripts/run_fabric_cicd.py
        env:
          FABRIC_CLIENT_ID: ${{ secrets.FABRIC_CLIENT_ID }}
          FABRIC_CLIENT_SECRET: ${{ secrets.FABRIC_CLIENT_SECRET }}
          FABRIC_TENANT_ID: ${{ secrets.FABRIC_TENANT_ID }}
          FABRIC_WORKSPACE_ID: ${{ secrets.FABRIC_WORKSPACE_ID }}
          TARGET_ENVIRONMENT_NAME: ${{ env.ENVIRONMENT }}
